name: CI/CD Pipeline

on:
  push:
    branches: [feature/github-actions]
    paths: 
      - 'khimoo-portfolio/**'
      - 'articles/**'
      - 'flake.nix'
      - 'flake.lock'

env:
  CARGO_TERM_COLOR: always
  NIX_CONFIG: "experimental-features = nix-command flakes"
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0
  # Nix environment variables
  NIXPKGS_ALLOW_UNFREE: 1
  FLAKE_LOCK_FALLBACK: 1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Nix environment
        uses: cachix/install-nix-action@v26
        with:
          install_url: https://releases.nixos.org/nix/nix-2.21.2/install
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            substituters = https://cache.nixos.org/ https://devenv.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw=
            warn-dirty = false
            
      - name: Setup Nix cache
        uses: cachix/cachix-action@v14
        with:
          name: devenv
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true
          
      - name: Test Nix development environment
        run: |
          echo "🦀 Testing Nix development environment..."
          nix develop --command echo "✅ nix develop works!"
          
      - name: Process articles
        run: |
          echo "Article processing step - to be implemented"
          # nix develop --command cargo run --bin process-articles
          
      - name: Generate link graph
        run: |
          echo "Link graph generation step - to be implemented"
          # nix develop --command cargo run --bin generate-link-graph
          
      - name: Build WebAssembly application
        run: |
          echo "🚀 Building WebAssembly application with Trunk..."
          cd khimoo-portfolio
          nix develop --command trunk build --release --public-url /khimoo.io/
          echo "✅ WebAssembly build completed"
          
      - name: Verify build artifacts
        run: |
          echo "🔍 Verifying build artifacts..."
          ls -la khimoo-portfolio/dist/
          echo "📊 Build artifact sizes:"
          du -h khimoo-portfolio/dist/
          echo "✅ Build verification completed"
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webassembly-build
          path: khimoo-portfolio/dist/
          retention-days: 30
          
      - name: Prepare deployment directory
        run: |
          echo "📁 Preparing deployment directory..."
          cp -r ./khimoo-portfolio/dist ./public
          cp ./public/index.html ./public/404.html
          echo "✅ Deployment directory prepared"
          echo "📊 Public directory contents:"
          ls -la ./public/
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy to GitHub Pages'
          
      - name: Verify deployment
        run: |
          echo "✅ GitHub Pages deployment completed"
          echo "🌐 Site will be available at: https://${{ github.repository_owner }}.github.io/khimoo.io/"
          echo "📝 Deployment commit: ${{ github.sha }}"
          echo "📁 Deployed files:"
          ls -la ./public/