name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: rustup target add wasm32-unknown-unknown

      - run: cargo install trunk

      - name: Build with trunk
        run: trunk build --release --public-url khimoo.io
        working-directory: ./khimoo-portfolio

      - name: Copy dist to public
        run: cp -r ./khimoo-portfolio/dist ./public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
