[build]
# Build configuration

[serve]
# Serve configuration
addresses = ["127.0.0.1"]
port = 8080
open = false

[watch]
# Watch for changes in these directories
watch = ["src/", "index.html"]
ignore = ["target/", "dist/", "data/"]